version: "3.9"

services:
  # ────────────────────────── Reverse-proxy ──────────────────────────
  proxy:
    image: traefik:v3.4            # reverse-proxy + HTTPS
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.le.acme.dnschallenge=true"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=duckdns"
      - "--certificatesresolvers.le.acme.email=cefcurlz@gmail.com"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certresolver=le"
      - "--entrypoints.websecure.http.tls.domains[0].main=${MY_DOMAIN}"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.${MY_DOMAIN}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik:/letsencrypt           # stocke les certifs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
    restart: unless-stopped
    networks: [cloud]

  # ───────────────────────────── Portainer ────────────────────────────
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${MY_DOMAIN}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
    networks: [cloud]

  # ──────────────────────────── MariaDB ───────────────────────────────
  nextclouddb:
    image: mariadb
    container_name: nextcloud-db
    environment:
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
    volumes:
      - nextclouddb:/var/lib/mysql
    restart: unless-stopped
    networks: [cloud]

  # ──────────────────────────── Nextcloud ─────────────────────────────
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    depends_on: [nextclouddb]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.${MY_DOMAIN}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
    volumes:
      - ./html:/var/www/html
      - ./data:/var/www/html/data
    restart: unless-stopped
    networks: [cloud]

  # ───────────────────────────── Jellyfin ─────────────────────────────
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${MY_DOMAIN}`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
    volumes:
      - jellyfin_data:/config
    restart: unless-stopped
    networks: [cloud]

# ─────────────────────────── Volumes & Réseau ─────────────────────────
volumes:
  portainer_data:
  nextclouddb:
  jellyfin_data:

networks:
  cloud:
    driver: bridge
